

spring:
  datasource:
    url: jdbc:postgresql://satao.db.elephantsql.com:5432/metfmtpv
    username: metfmtpv
    password: mkggTky5LX-IinIpnOli2b0f_ExefSk3
    driver-class-name: org.postgresql.Driver